package view;

import java.awt.Dimension;

/**
 *
 * @author Programador Evanei Freitas.
 */
public class FrmInterAtualizarEstoque extends javax.swing.JInternalFrame {

    public FrmInterAtualizarEstoque() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gerenciar Estoques dos Produtos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_walppaper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_walppaper.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_walppaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atualizar Estoque");
        jPanel_walppaper.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 190, -1));

        getContentPane().add(jPanel_walppaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_walppaper;
    // End of variables declaration//GEN-END:variables
}
