package view;

import controller.Controller_Cliente;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author Programador Evanei Freitas.
 */
public class FrmInterUsuario extends javax.swing.JInternalFrame {

    public FrmInterUsuario() {
        initComponents();
        this.setSize(new Dimension(788, 498));
        this.setTitle("Novo Usuário");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        txt_Cpf = new javax.swing.JTextField();
        txt_Celular = new javax.swing.JTextField();
        txt_Apelido = new javax.swing.JTextField();
        jButton_SalvarCliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        txt_Descricao2 = new javax.swing.JTextField();
        txt_Descricao3 = new javax.swing.JTextField();
        txt_Endereco = new javax.swing.JTextField();
        txt_Telefone1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1_Walpapper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Novo Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apelido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cpf:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Endereço:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 80, -1));

        txt_Nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, -1));

        txt_Cpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, -1));

        txt_Celular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 265, 240, -1));

        txt_Apelido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 240, -1));

        jButton_SalvarCliente.setBackground(new java.awt.Color(0, 204, 204));
        jButton_SalvarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SalvarCliente.setText("Salvar");
        jButton_SalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_SalvarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 240, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 310, 400));

        txt_telefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, -1));

        txt_Descricao2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Descricao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, -1));

        txt_Descricao3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Descricao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, -1));

        txt_Endereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 240, -1));

        txt_Telefone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_Telefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefone:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 80, -1));

        jLabel1_Walpapper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        jPanel1.add(jLabel1_Walpapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 730, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarClienteActionPerformed
        // Código do Botão Salvar Cliente.
        Cliente cliente = new Cliente();
        Controller_Cliente controllerCliente = new Controller_Cliente();

        //Validação dos Campos do Formulário.
        if (!txt_Nome.getText().isEmpty() && !txt_Apelido.getText().isEmpty() && !txt_Cpf.getText().isEmpty()
                && !txt_telefone.getText().isEmpty() && !txt_Celular.getText().isEmpty() && !txt_Endereco.getText().isEmpty()) {

            if (!controllerCliente.existeCliente(txt_Cpf.getText().trim())) {
                cliente.setNome(txt_Nome.getText().trim());
                cliente.setApelido(txt_Apelido.getText().trim());
                cliente.setCpf(txt_Cpf.getText().trim());
                cliente.setTelefone(txt_telefone.getText().trim());
                cliente.setCelular(txt_Celular.getText().trim());
                cliente.setEndereco(txt_Endereco.getText().trim());
                cliente.setEstado(1);

                if (controllerCliente.SalvarCliente(cliente)) {
                    JOptionPane.showMessageDialog(null, "Cliente Salvo com Sucesso!");
                    txt_Nome.setBackground(Color.white);
                    txt_Apelido.setBackground(Color.white);
                    txt_Cpf.setBackground(Color.white);
                    txt_telefone.setBackground(Color.white);
                    txt_Celular.setBackground(Color.white);
                    txt_Endereco.setBackground(Color.white);

                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar Salvar Cliente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Atenção: CPF já cadastrado no sistema!");
                txt_Nome.setBackground(Color.white);
                txt_Apelido.setBackground(Color.white);
                txt_Cpf.setBackground(Color.white);
                txt_telefone.setBackground(Color.white);
                txt_Celular.setBackground(Color.white);
                txt_Endereco.setBackground(Color.white);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos!");
            txt_Nome.setBackground(Color.red);
            txt_Apelido.setBackground(Color.red);
            txt_Cpf.setBackground(Color.red);
            txt_telefone.setBackground(Color.red);
            txt_Celular.setBackground(Color.red);
            txt_Endereco.setBackground(Color.red);
        }
        this.limparCampos();
    }//GEN-LAST:event_jButton_SalvarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SalvarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Walpapper;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Apelido;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_Cpf;
    private javax.swing.JTextField txt_Descricao2;
    private javax.swing.JTextField txt_Descricao3;
    private javax.swing.JTextField txt_Endereco;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Telefone1;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    /**
     ***************************************************************
     * Método para limpar Campos.
     * **************************************************************
     */
    private void limparCampos() {
        txt_Nome.setText("");
        txt_Apelido.setText("");
        txt_Cpf.setText("");
        txt_telefone.setText("");
        txt_Celular.setText("");
        txt_Endereco.setText("");
    }

}
