package view;

import controller.Controller_Categoria;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import model.Categoria;

/**
 *
 * @author Programador Evanei Freitas.
 */
public class FrmInterCategoria extends javax.swing.JInternalFrame {

    public FrmInterCategoria() {
        initComponents();
        this.setSize(new Dimension(567, 294));
        this.setTitle("Nova Categoria");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        jButton_SalvarCategoria = new javax.swing.JButton();
        jLabel_walpepper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nova Categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descrição Categoria :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_descricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 220, -1));

        jButton_SalvarCategoria.setBackground(new java.awt.Color(0, 204, 204));
        jButton_SalvarCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SalvarCategoria.setText("Salvar Categoria");
        jButton_SalvarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_SalvarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 220, 40));

        jLabel_walpepper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_walpepper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalvarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarCategoriaActionPerformed
        //Código do botão Salvar Categorias.
        salvarCategoria();

    }//GEN-LAST:event_jButton_SalvarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SalvarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_walpepper;
    private javax.swing.JTextField txt_descricao;
    // End of variables declaration//GEN-END:variables

    //Metodo Salvar(Categorias no Banco de Dados ) Categoria
    public void salvarCategoria() {
        Categoria categoria = new Categoria();
        Controller_Categoria controllerCategoria = new Controller_Categoria();

        //Validação de Campos Vazios.
        if (txt_descricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo Descrição Categoria!");
        } else {
            if (!controllerCategoria.existeCategoria(txt_descricao.getText().trim())) {
                categoria.setDescricao(txt_descricao.getText().trim());
                categoria.setEstado(1);
                if (controllerCategoria.guardar(categoria)) {
                    JOptionPane.showMessageDialog(null, "Categoria Salva Com Sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar Salvar Categoria!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Já existe esta Categoria Gravada no Banco de Dados!");
            }

        }

        //Limpar campos
        txt_descricao.setText("");

    }

}
